# Nebula Configuration Template for LuciVerse Overlay Network
# Genesis Bond: ACTIVE @ ${FREQUENCY} Hz
# Generated by provision-listener for ${HOSTNAME}
#
# This template is processed by provision-listener.py to generate
# per-node Nebula configurations during PXE boot.

pki:
  ca: /etc/nebula/ca.crt
  cert: /etc/nebula/host.crt
  key: /etc/nebula/host.key

static_host_map:
  # Lighthouse nodes (CORE tier)
  "10.100.1.145": ["192.168.1.145:4242"]  # zbook - Primary lighthouse

lighthouse:
  am_lighthouse: ${IS_LIGHTHOUSE}
  serve_dns: ${SERVE_DNS}
  interval: 60
  hosts:
    - "10.100.1.145"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true
  respond: true
  delay: 1s

# Tier-based relay configuration
relay:
  am_relay: ${IS_RELAY}
  use_relays: true
  relays:
    - "10.100.1.145"  # CORE lighthouse

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300
  routes:
  unsafe_routes:
${UNSAFE_ROUTES}

logging:
  level: info
  format: text

# Firewall rules based on tier
firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m
    max_connections: 100000

  # Outbound rules - allow all by default
  outbound:
    - port: any
      proto: any
      host: any

  # Inbound rules - tier-based access control
  inbound:
    # Allow ICMP from anyone for health checks
    - port: any
      proto: icmp
      host: any

    # Allow SSH from CORE tier only
    - port: 22
      proto: tcp
      groups:
        - core
        - infrastructure

    # Allow agent ports based on tier
${INBOUND_RULES}
