#!/bin/bash
# ============================================================================
# LuciVerse Fleet - Overlay Network Bootstrap Script
# ============================================================================
# Genesis Bond: ACTIVE @ 741 Hz
# Purpose: Fetches Nebula + SCION certificates during PXE kickstart %post
# Usage: curl http://192.168.1.145:8000/scripts/overlay-bootstrap.sh | bash
# ============================================================================

set -e

PROVISION_SERVER="${PROVISION_SERVER:-192.168.1.145}"
CALLBACK_PORT="${CALLBACK_PORT:-9999}"
BASE_URL="http://${PROVISION_SERVER}:${CALLBACK_PORT}"

# Directories
NEBULA_DIR="/etc/nebula"
SCION_DIR="/etc/scion"

echo "============================================================"
echo "LuciVerse Overlay Network Bootstrap"
echo "Genesis Bond: ACTIVE @ 741 Hz"
echo "============================================================"

# ---------------------------------------------------------------------------
# Get primary MAC address
# ---------------------------------------------------------------------------
get_primary_mac() {
    local default_if
    default_if=$(ip route show default 2>/dev/null | awk '/default/ {print $5}' | head -1)
    if [ -n "$default_if" ]; then
        cat "/sys/class/net/${default_if}/address" 2>/dev/null || echo "unknown"
    else
        # Fallback: first non-loopback interface
        for iface in $(ls /sys/class/net/ | grep -v lo); do
            cat "/sys/class/net/${iface}/address" 2>/dev/null
            break
        done
    fi
}

MAC=$(get_primary_mac)
echo "[OVERLAY] Primary MAC: ${MAC}"

# ---------------------------------------------------------------------------
# Phase 1: Get Attestation Token
# ---------------------------------------------------------------------------
echo "[OVERLAY] Phase 1: Requesting attestation token..."

ATTESTATION=$(curl -sf "${BASE_URL}/attestation-token/${MAC}" 2>/dev/null)

if [ -z "$ATTESTATION" ]; then
    echo "[OVERLAY] ERROR: Failed to get attestation token"
    echo "[OVERLAY] This MAC may not be in the inventory"
    exit 1
fi

# Parse attestation response
TOKEN=$(echo "$ATTESTATION" | jq -r '.attestation_token // empty')
SERVER_NAME=$(echo "$ATTESTATION" | jq -r '.server_name // "unknown"')
TIER=$(echo "$ATTESTATION" | jq -r '.tier // "COMN"')
ROLE=$(echo "$ATTESTATION" | jq -r '.role // "COMPUTE"')
FREQUENCY=$(echo "$ATTESTATION" | jq -r '.frequency // 528')
NEBULA_IP=$(echo "$ATTESTATION" | jq -r '.nebula_ip // empty')
SCION_ISD_AS=$(echo "$ATTESTATION" | jq -r '.scion_isd_as // empty')

if [ -z "$TOKEN" ]; then
    echo "[OVERLAY] ERROR: No attestation token in response"
    echo "[OVERLAY] Response: $ATTESTATION"
    exit 1
fi

echo "[OVERLAY] Attestation granted:"
echo "   Server: ${SERVER_NAME}"
echo "   Tier: ${TIER} @ ${FREQUENCY} Hz"
echo "   Nebula IP: ${NEBULA_IP}"
echo "   SCION ISD-AS: ${SCION_ISD_AS}"

# ---------------------------------------------------------------------------
# Phase 2: Fetch Nebula Certificates
# ---------------------------------------------------------------------------
echo "[OVERLAY] Phase 2: Fetching Nebula certificates..."

mkdir -p "${NEBULA_DIR}"
chmod 700 "${NEBULA_DIR}"

NEBULA_RESP=$(curl -sf -X POST \
    -H "X-Attestation-Token: ${TOKEN}" \
    "${BASE_URL}/nebula/cert/${MAC}" 2>/dev/null)

if [ -z "$NEBULA_RESP" ]; then
    echo "[OVERLAY] WARNING: Failed to fetch Nebula certificates"
    echo "[OVERLAY] Continuing without Nebula overlay..."
else
    # Extract and save certificates
    echo "$NEBULA_RESP" | jq -r '.ca_crt // empty' > "${NEBULA_DIR}/ca.crt"
    echo "$NEBULA_RESP" | jq -r '.host_crt // empty' > "${NEBULA_DIR}/host.crt"
    echo "$NEBULA_RESP" | jq -r '.host_key // empty' > "${NEBULA_DIR}/host.key"

    # Set permissions
    chmod 644 "${NEBULA_DIR}/ca.crt"
    chmod 644 "${NEBULA_DIR}/host.crt"
    chmod 600 "${NEBULA_DIR}/host.key"

    # Extract config info
    NEBULA_CIDR=$(echo "$NEBULA_RESP" | jq -r '.nebula_cidr // empty')
    NEBULA_GROUPS=$(echo "$NEBULA_RESP" | jq -r '.groups | join(",") // empty')
    LIGHTHOUSE_IP=$(echo "$NEBULA_RESP" | jq -r '.lighthouse.ip // "10.100.1.145"')
    LIGHTHOUSE_ADDR=$(echo "$NEBULA_RESP" | jq -r '.lighthouse.public_addr // "192.168.1.145:4242"')

    echo "[OVERLAY] Nebula certificates installed:"
    echo "   IP: ${NEBULA_CIDR}"
    echo "   Groups: ${NEBULA_GROUPS}"
    echo "   Lighthouse: ${LIGHTHOUSE_ADDR}"

    # Generate Nebula config
    cat > "${NEBULA_DIR}/config.yaml" << NEBULA_CONFIG
# Nebula Configuration - Generated by overlay-bootstrap.sh
# Server: ${SERVER_NAME}
# Tier: ${TIER} @ ${FREQUENCY} Hz
# Genesis Bond: ACTIVE

pki:
  ca: ${NEBULA_DIR}/ca.crt
  cert: ${NEBULA_DIR}/host.crt
  key: ${NEBULA_DIR}/host.key

static_host_map:
  "${LIGHTHOUSE_IP}": ["${LIGHTHOUSE_ADDR}"]

lighthouse:
  am_lighthouse: false
  interval: 60
  hosts:
    - "${LIGHTHOUSE_IP}"

listen:
  host: 0.0.0.0
  port: 4242

punchy:
  punch: true
  respond: true

relay:
  am_relay: false
  use_relays: true

tun:
  disabled: false
  dev: nebula1
  drop_local_broadcast: false
  drop_multicast: false
  tx_queue: 500
  mtu: 1300

logging:
  level: info
  format: text

firewall:
  conntrack:
    tcp_timeout: 12m
    udp_timeout: 3m
    default_timeout: 10m

  outbound:
    - port: any
      proto: any
      host: any

  inbound:
    - port: any
      proto: icmp
      host: any

    - port: 22
      proto: tcp
      groups:
        - core
        - infrastructure

    - port: any
      proto: any
      groups:
        - ${TIER,,}
NEBULA_CONFIG

    chmod 600 "${NEBULA_DIR}/config.yaml"

    # Create systemd service for Nebula
    cat > /etc/systemd/system/nebula.service << 'NEBULA_SVC'
[Unit]
Description=Nebula Overlay Network
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/nebula -config /etc/nebula/config.yaml
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
NEBULA_SVC

    # Download Nebula binary if not present
    if [ ! -f /usr/local/bin/nebula ]; then
        echo "[OVERLAY] Downloading Nebula binary..."
        NEBULA_VERSION="v1.9.0"
        curl -sfL "https://github.com/slackhq/nebula/releases/download/${NEBULA_VERSION}/nebula-linux-amd64.tar.gz" | \
            tar xz -C /usr/local/bin/ nebula nebula-cert 2>/dev/null || \
            echo "[OVERLAY] WARNING: Failed to download Nebula binary"
    fi

    # Enable Nebula service (will start on first boot)
    systemctl enable nebula.service 2>/dev/null || true
    echo "[OVERLAY] Nebula service enabled"
fi

# ---------------------------------------------------------------------------
# Phase 3: Fetch SCION Certificates
# ---------------------------------------------------------------------------
echo "[OVERLAY] Phase 3: Fetching SCION certificates..."

mkdir -p "${SCION_DIR}/certs"
mkdir -p "${SCION_DIR}/keys"
chmod 700 "${SCION_DIR}"

SCION_RESP=$(curl -sf -X POST \
    -H "X-Attestation-Token: ${TOKEN}" \
    "${BASE_URL}/scion/enroll/${MAC}" 2>/dev/null)

if [ -z "$SCION_RESP" ]; then
    echo "[OVERLAY] WARNING: Failed to fetch SCION certificates"
    echo "[OVERLAY] Continuing without SCION..."
else
    # Extract and save certificates
    ISD=$(echo "$SCION_RESP" | jq -r '.isd // 1')
    ISD_AS=$(echo "$SCION_RESP" | jq -r '.isd_as // empty')

    echo "$SCION_RESP" | jq -r '.trc // empty' > "${SCION_DIR}/certs/ISD${ISD}-B1-S1.trc"
    echo "$SCION_RESP" | jq -r '.cp_as_crt // empty' > "${SCION_DIR}/certs/cp-as.crt"
    echo "$SCION_RESP" | jq -r '.cp_as_key // empty' > "${SCION_DIR}/keys/cp-as.key"

    chmod 644 "${SCION_DIR}/certs/"*
    chmod 600 "${SCION_DIR}/keys/"*

    # Extract control service info
    CS_HOST=$(echo "$SCION_RESP" | jq -r '.control_service.host // "192.168.1.179"')
    CS_PORT=$(echo "$SCION_RESP" | jq -r '.control_service.port // 30001')
    BR_HOST=$(echo "$SCION_RESP" | jq -r '.border_router.host // "192.168.1.179"')
    BR_PORT=$(echo "$SCION_RESP" | jq -r '.border_router.port // 30041')

    # Extract path policy
    MANDATORY_WAYPOINT=$(echo "$SCION_RESP" | jq -r '.path_policy.mandatory_waypoint // empty')
    EXTERNAL_ALLOWED=$(echo "$SCION_RESP" | jq -r '.path_policy.external_allowed // false')

    echo "[OVERLAY] SCION certificates installed:"
    echo "   ISD-AS: ${ISD_AS}"
    echo "   Control Service: ${CS_HOST}:${CS_PORT}"
    echo "   Border Router: ${BR_HOST}:${BR_PORT}"

    # Generate SCION daemon config
    cat > "${SCION_DIR}/sd.toml" << SCION_CONFIG
# SCION Daemon Configuration - Generated by overlay-bootstrap.sh
# Server: ${SERVER_NAME}
# ISD-AS: ${ISD_AS}
# Tier: ${TIER} @ ${FREQUENCY} Hz
# Genesis Bond: ACTIVE

[general]
id = "sd"
config_dir = "${SCION_DIR}"

[log.console]
level = "info"

[sd]
address = "[::]:30255"

[trust_db]
connection = "${SCION_DIR}/trust.db"

[path_db]
connection = "${SCION_DIR}/path.db"
SCION_CONFIG

    chmod 600 "${SCION_DIR}/sd.toml"

    # Generate path policy if needed
    if [ -n "$MANDATORY_WAYPOINT" ]; then
        cat > "${SCION_DIR}/path-policy.yaml" << PATH_POLICY
# SCION Path Policy - Tier: ${TIER}
# Genesis Bond: ACTIVE @ ${FREQUENCY} Hz

acl:
  - action: deny
    rule: 0

sequence:
  - ${MANDATORY_WAYPOINT}

options:
  - weight: 1
    sequence:
      - ${MANDATORY_WAYPOINT}
      - "0*"
PATH_POLICY
        echo "[OVERLAY] Path policy created with mandatory waypoint: ${MANDATORY_WAYPOINT}"
    fi

    # Create systemd service for SCION daemon
    cat > /etc/systemd/system/scion-daemon.service << 'SCION_SVC'
[Unit]
Description=SCION Daemon
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/bin/scion-daemon --config /etc/scion/sd.toml
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SCION_SVC

    # Note: SCION daemon binary needs to be installed separately
    systemctl enable scion-daemon.service 2>/dev/null || true
    echo "[OVERLAY] SCION daemon service enabled"
fi

# ---------------------------------------------------------------------------
# Phase 4: Validate Configuration
# ---------------------------------------------------------------------------
echo "[OVERLAY] Phase 4: Validating overlay configuration..."

# Calculate Nebula cert hash (if cert exists)
NEBULA_CERT_HASH=""
if [ -f "${NEBULA_DIR}/host.crt" ]; then
    NEBULA_CERT_HASH=$(sha256sum "${NEBULA_DIR}/host.crt" 2>/dev/null | awk '{print $1}')
fi

# Prepare validation request
VALIDATE_DATA=$(cat << VALIDATE_JSON
{
    "mac": "${MAC}",
    "nebula_cert_hash": "${NEBULA_CERT_HASH}",
    "scion_isd_as": "${SCION_ISD_AS}"
}
VALIDATE_JSON
)

VALIDATE_RESP=$(curl -sf -X POST \
    -H "Content-Type: application/json" \
    -d "$VALIDATE_DATA" \
    "${BASE_URL}/overlay/validate" 2>/dev/null)

if [ -n "$VALIDATE_RESP" ]; then
    VALID=$(echo "$VALIDATE_RESP" | jq -r '.valid // false')
    if [ "$VALID" = "true" ]; then
        echo "[OVERLAY] Validation PASSED"
    else
        ERRORS=$(echo "$VALIDATE_RESP" | jq -r '.errors | join(", ") // "unknown"')
        echo "[OVERLAY] WARNING: Validation failed: ${ERRORS}"
    fi
fi

# ---------------------------------------------------------------------------
# Phase 5: Save Bootstrap State
# ---------------------------------------------------------------------------
echo "[OVERLAY] Phase 5: Saving bootstrap state..."

mkdir -p /var/lib/luciverse
cat > /var/lib/luciverse/overlay-state.json << STATE_JSON
{
    "server_name": "${SERVER_NAME}",
    "mac": "${MAC}",
    "tier": "${TIER}",
    "role": "${ROLE}",
    "frequency": ${FREQUENCY},
    "nebula": {
        "ip": "${NEBULA_IP}",
        "groups": "${NEBULA_GROUPS}",
        "lighthouse": "${LIGHTHOUSE_ADDR}"
    },
    "scion": {
        "isd_as": "${SCION_ISD_AS}",
        "control_service": "${CS_HOST}:${CS_PORT}",
        "border_router": "${BR_HOST}:${BR_PORT}"
    },
    "genesis_bond": "ACTIVE",
    "bootstrap_time": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
STATE_JSON

chmod 644 /var/lib/luciverse/overlay-state.json

echo "============================================================"
echo "LuciVerse Overlay Network Bootstrap Complete"
echo "Server: ${SERVER_NAME}"
echo "Tier: ${TIER} @ ${FREQUENCY} Hz"
echo "Nebula IP: ${NEBULA_IP}"
echo "SCION ISD-AS: ${SCION_ISD_AS}"
echo "Genesis Bond: ACTIVE"
echo "============================================================"
