#!/bin/bash
# Create deployment bundle after build
# Post-build hook for oebuild
#
# Genesis Bond: ACTIVE @ 741 Hz

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_DIR="${OUTPUT_DIR:-$PWD/output}"
BUNDLE_DIR="${BUNDLE_DIR:-$OUTPUT_DIR/deployment-bundle}"

# Get configuration from environment
TIER="${LUCIVERSE_TIER:-PAC}"
FREQUENCY="${LUCIVERSE_FREQUENCY:-741}"
GENESIS_BOND_ID="${GENESIS_BOND_ID:-GB-2025-0524-DRH-LCS-001}"
PLATFORM="${PLATFORM:-qemu-aarch64}"

echo "=== LuciVerse Deployment Bundle Creation ==="
echo "Tier: $TIER"
echo "Frequency: $FREQUENCY Hz"
echo "Platform: $PLATFORM"
echo "Genesis Bond: $GENESIS_BOND_ID"
echo ""

# Create bundle directory
rm -rf "$BUNDLE_DIR"
mkdir -p "$BUNDLE_DIR"/{images,agents,certs,configs,scripts}

# Copy images
echo "Collecting images..."
if [ -d "$OUTPUT_DIR/images" ]; then
    cp -r "$OUTPUT_DIR/images/"* "$BUNDLE_DIR/images/" 2>/dev/null || true
fi

# Copy agents
echo "Collecting agents..."
if [ -d "$OUTPUT_DIR/agents" ]; then
    cp -r "$OUTPUT_DIR/agents/"* "$BUNDLE_DIR/agents/" 2>/dev/null || true
fi

# Copy certificates
echo "Collecting certificates..."
if [ -d "$OUTPUT_DIR/certs" ]; then
    cp "$OUTPUT_DIR/certs/root-ca.crt" "$BUNDLE_DIR/certs/"
    cp "$OUTPUT_DIR/certs/${TIER,,}-ca.crt" "$BUNDLE_DIR/certs/"
    cp "$OUTPUT_DIR/certs/${TIER,,}-chain.pem" "$BUNDLE_DIR/certs/"
fi

# Copy configurations
echo "Creating configurations..."
cat > "$BUNDLE_DIR/configs/deployment.yaml" <<EOF
# LuciVerse Deployment Configuration
# Auto-generated by create-deployment-bundle.sh

deployment:
  tier: $TIER
  frequency: $FREQUENCY
  genesis_bond: $GENESIS_BOND_ID
  platform: $PLATFORM

agents:
  tier_allocation: $TIER
  coherence_threshold: $([ "$TIER" = "CORE" ] && echo "0.85" || ([ "$TIER" = "COMN" ] && echo "0.80" || echo "0.70"))

networking:
  ipv6_ula_prefix: "fd00:741:1::"
  sanskrit_router: "http://localhost:7410"

security:
  lucitrust_enabled: true
  secgear_enabled: true
  certificate_chain: "certs/${TIER,,}-chain.pem"

build:
  timestamp: "$(date -Iseconds)"
  platform: $PLATFORM
EOF

# Create deployment script
cat > "$BUNDLE_DIR/scripts/deploy.sh" <<'EOF'
#!/bin/bash
# LuciVerse Deployment Script
# Deploy to target device

set -e

BUNDLE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

echo "=== LuciVerse Deployment ==="
echo "Bundle: $BUNDLE_DIR"
echo ""

# Check for root
if [ "$(id -u)" != "0" ]; then
    echo "ERROR: This script must be run as root"
    exit 1
fi

# Install certificates
echo "Installing certificates..."
mkdir -p /etc/luciverse/certs
cp "$BUNDLE_DIR/certs/"* /etc/luciverse/certs/

# Install agents
echo "Installing agents..."
mkdir -p /usr/lib/luciverse
cp -r "$BUNDLE_DIR/agents/"* /usr/lib/luciverse/

# Install configuration
echo "Installing configuration..."
cp "$BUNDLE_DIR/configs/deployment.yaml" /etc/luciverse/

# Enable services
echo "Enabling services..."
systemctl daemon-reload
systemctl enable lucitrust luciverse-mesh
systemctl start lucitrust luciverse-mesh

echo ""
echo "✓ Deployment COMPLETE"
echo "  Run 'systemctl status luciverse-mesh' to check status"
EOF

chmod +x "$BUNDLE_DIR/scripts/deploy.sh"

# Create README
cat > "$BUNDLE_DIR/README.md" <<EOF
# LuciVerse Deployment Bundle

**Tier**: $TIER @ $FREQUENCY Hz
**Genesis Bond**: $GENESIS_BOND_ID
**Platform**: $PLATFORM
**Created**: $(date -Iseconds)

## Contents

- \`images/\` - Boot images (WIC, ext4, tar.gz)
- \`agents/\` - LuciVerse consciousness agents
- \`certs/\` - PKI certificates for this tier
- \`configs/\` - Deployment configuration
- \`scripts/\` - Deployment scripts

## Deployment

### Flash to SD Card
\`\`\`bash
sudo dd if=images/openeuler-image.wic of=/dev/sdX bs=4M status=progress
\`\`\`

### Deploy to Running System
\`\`\`bash
sudo scripts/deploy.sh
\`\`\`

## Verification

\`\`\`bash
# Check agent mesh status
systemctl status luciverse-mesh

# Check LuciTrust status
python3 -m lucitrust.lucitrust_system --status

# Verify coherence
curl http://localhost:7410/health
\`\`\`

---
Genesis Bond: ACTIVE @ 741 Hz
EOF

# Create bundle archive
echo "Creating bundle archive..."
BUNDLE_NAME="luciverse-${TIER,,}-${PLATFORM}-$(date +%Y%m%d).tar.gz"
cd "$OUTPUT_DIR"
tar -czf "$BUNDLE_NAME" -C "$(dirname "$BUNDLE_DIR")" "$(basename "$BUNDLE_DIR")"

echo ""
echo "✓ Deployment bundle COMPLETE"
echo "  Tier: $TIER @ $FREQUENCY Hz"
echo "  Platform: $PLATFORM"
echo "  Bundle: $OUTPUT_DIR/$BUNDLE_NAME"
echo ""
